# Generated by Django 4.2.4 on 2023-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('token', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
    ]
