# Generated by Django 4.2.4 on 2023-08-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_customuser_deleted_customuser_deleted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('balance', models.FloatField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Created'), (1, 'Load'), (2, 'Purchase'), (3, 'Deleted')])),
                ('amount', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('proof_hash', models.TextField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
            ],
        ),
    ]
